### ISSUE TITLE
Actinia docker image with latest GRASS GIS code

### ISSUE THREAD

**Issue by jonas-eberle** [actinia-org/actinia-core#241]
Hi all, 

is there a possibility to run an Actinia Docker container together with a recent GRASS GIS (last commit of GRASS GIS main repository)?

There is already a Docker container with recent GRASS GIS code (`grass-py3-pdal:latest-ubuntu`), but I didnt't find an Actinia Dockerfile based on this image. 

Thanks
Jonas

**Comment by mmacata** [comment]
Hi Jonas, not out-of-the-box. The actinia build is only triggered for a release or push to main branch.
I restarted the last github action manually which did the docker builds for main branch and some jobs already run through:
For example the actinia-core image with tag g79-latest-alpine now contains 
```
version=8.0.dev
date=2021
revision=75dd60a
build_date=2021-09-14
```
which is what you are looking for. If you prefer the ubuntu image, it should be pushed soon as well.

**Comment by mmacata** [comment]
This could be done via GHA scheduler, but we find it is overhead to build a new actinia image e.g. every day. Usually it is feasable to have a new GRASS GIS version for new changes in actinia and anything on top can be done manually.
Therefore closing this.

**Comment by jonas-eberle** [comment]
@mmacata Thanks for the info. I think it is not necessary to have an Actinia container always with the latest GRASS GIS, but it would be good to have a Dockerfile / docker-compose that can be used/build locally with the latest GRASS GIS. Maybe this is already available, but would be great to have a documentation about this.

**Comment by mmacata** [comment]
Ok, I see. A Dockerfile is available for this https://github.com/mundialis/actinia_core/tree/main/docker/actinia-core-alpine but manual steps are required:
* change `grass-py3-pdal:stable-alpine` to `grass-py3-pdal:latest-alpine` in docker/actinia-core-alpine/Dockerfile
* reuse [docker-compose-dev.yml](https://github.com/mundialis/actinia_core/blob/main/docker/docker-compose-dev.yml) and replace 
```
build:
      context: actinia-core-dev/
```
```
build:
      context: actinia-core-alpine/
```
* build it with ` docker-compose -f docker/docker-compose-dev.yml build --pull`
* run it with `docker-compose -f docker/docker-compose-dev.yml up`

I will reopen this until it makes it into the documentation.

**Comment by mmacata** [comment]
Documented here https://github.com/actinia-org/actinia-core/blob/main/docker/README.md#installation-with-most-recent-grass-gis-version
