### ISSUE TITLE
latest release missing from Pypi

### ISSUE THREAD

**Issue by kalxas** [actinia-org/actinia-core#370]
Would it be possible to upload the latest version on Pypi or is the project docker only now?

**Comment by mmacata** [comment]
Work in progress #373 but still some obstacles. Meanwhile, could it be an option to use the python wheels attached to the releases?

Then it would be 
```
pip3 install "actinia-core @ https://github.com/mundialis/actinia_core/releases/download/4.2.0/actinia_core-4.2.0-py2.py3-none-any.whl"
pip3 install "actinia-api @ https://github.com/mundialis/actinia-api/releases/download/3.2.0/actinia_api-3.2.0-py3-none-any.whl"
pip3 install -r https://raw.githubusercontent.com/mundialis/actinia_core/main/requirements.txt
python3 -m actinia_core.main
```

A running redis instance is needed at localhost. If error appears: `PermissionError: [Errno 13] Permission denied: '/etc/default/actinia'` the config path can be adjusted, the file doesn't need to exist, e.g. `export DEFAULT_CONFIG_PATH=~$HOME/actinia.cfg`.

**Comment by kalxas** [comment]
https://trac.osgeo.org/osgeolive/ticket/2383#comment:5

**Comment by neteler** [comment]
HI @kalxas Did you eventually success with the pip installation of actinia?

**Comment by kalxas** [comment]
Unfortunately no

**Comment by neteler** [comment]
New attempt here:
https://github.com/OSGeo/OSGeoLive/pull/366
