### ISSUE TITLE
Black for actinia

### ISSUE THREAD

**Issue by anikaweinmann** [actinia-org/actinia-core#372]
We want to use `black` to beautify actinia code.

We want to use some black in Workflows, so that workflows fails if the code is not black conform.
Before the workflow is active we need to do black about the whole code.

**Comment by neteler** [comment]
FYI, here the related GRASS GIS black workflow:

https://github.com/OSGeo/grass/blob/main/.github/workflows/black.yml

**Comment by anikaweinmann** [comment]
actinia-core now has a black GHA worflow: https://github.com/mundialis/actinia_core/blob/main/.github/workflows/black.yml

For the plugins it has to be added:
- [actinia_statistic_plugin](https://github.com/mundialis/actinia_statistic_plugin/tree/main/.github/workflows)
- actinia-stac-plugin ? It uses a [mega-linter](https://github.com/mundialis/actinia-stac-plugin/blob/main/.github/workflows/mega-linter.yml) @mmacata is then black still needed?
- [actinia-module-plugin](https://github.com/mundialis/actinia-module-plugin/tree/main/.github/workflows)
- [actinia-api](https://github.com/mundialis/actinia-api/blob/main/.github/workflows/black.yml)
- [actinia-parallel-plugin](https://github.com/mundialis/actinia-parallel-plugin/tree/main/.github/workflows)
- [actinia-example-plugin](https://github.com/mundialis/actinia-example-plugin/tree/main/.github/workflows)
- [actinia_satellite_plugin](https://github.com/mundialis/actinia_satellite_plugin/tree/main/.github/workflows)
- [actinia-tiling-plugin](https://github.com/mundialis/actinia-tiling-plugin/tree/main/.github/workflows)
- [actinia-metadata-plugin](https://github.com/mundialis/actinia-metadata-plugin/tree/main/.github/workflows)
- [actinia-gdi](https://github.com/mundialis/actinia-gdi/tree/master/.github/workflows)

Allready done for:
- [actinia-api](https://github.com/mundialis/actinia-api/blob/main/.github/workflows/black.yml)

**Comment by mmacata** [comment]
From my point of view, megalinter is also fine, but I don't know if this would also change files like black does. I would suggest to not add black there and see how we get along with megalinter!?

**Comment by mmacata** [comment]
See #469 (maybe close this one here)
