### ISSUE TITLE
Zenodo upload broken (after GitHub ORG change?) and DOI needed update

### ISSUE THREAD

**Issue by neteler** [actinia-org/actinia-core#417]
The automated upload of actinia-core to Zenodo.org is broken for a while (Dec. 2022) which needs to be fixed. 

Also the DOI of actinia-core in `CITATION.cff` is incorrect at:

https://github.com/actinia-org/actinia-core/blob/506e1b04efd4225470f7a9c50fe659e5f6b499d0/CITATION.cff#L9

it should be changed to
[10.5281/zenodo.7437895](https://doi.org/10.5281/zenodo.7437895)

Also here:
https://github.com/actinia-org/actinia-core/wiki#citing-actinia

**Comment by neteler** [comment]
The reason is different, see

https://lists.osgeo.org/pipermail/sac/2023-March/015088.html

**Comment by neteler** [comment]
DOI corrected in 53cb7bb329f7e6f9e2c37b0e4cd098085b109832.

Remains the yet broken actinia-core publishing on Zenodo which is probably an OSGeo GitHub OAuth App access problem.
Since GDAL ([DOI](https://doi.org/10.5281/zenodo.5884351)) has solved it: does @rouault have a bugfix suggestion for us?

**Comment by rouault** [comment]
- In https://zenodo.org/account/settings/github/ , make sure that the repository you're interested in appears in top "Enabled repositories"
- In https://github.com/organizations/OSGeo/settings/oauth_application_policy I had switched to the looser "Policy: No restrictions", but I'm not sure this was needed. I did that, before realizing that in Zenodo the repository wasn't enabled.

**Comment by neteler** [comment]
So I changed:
 
Settings > Third-party Access > Oauth application policy
(https://github.com/organizations/actinia-org/settings/oauth_application_policy)

from
 Policy: Access restricted --> Remove restrictions -> Policy: No restrictions

Now, I finally see `actinia-org/actinia-core` under "Enabled Repositories" in:
https://zenodo.org/account/settings/github/

and it is switched to "on".

Now let's hope the best for the next actinia-core release!

Thanks for the insights, @rouault!

**Comment by mmacata** [comment]
Success :) https://zenodo.org/record/8014388

**Comment by neteler** [comment]
The DOI creation at Zenodo.org is broken again:

https://zenodo.org/account/settings/github/repository/actinia-org/actinia-core

![image](https://github.com/actinia-org/actinia-core/assets/1295172/f72888d5-012f-4314-936b-359c907fb1e4)

**Comment by neteler** [comment]
I have redone the authorization:

- Connect Github releases to Zenodo
    - GH login (using mine since we no longer have a mundialis GH user): https://github.com/login
- Zenodo login: info ATTT mundialis.de: https://zenodo.org/
- link GH: https://zenodo.org/account/settings/linkedaccounts/
    - --> GitHub [X]
- setup GH repo: https://zenodo.org/account/settings/github/
    - --> actinia-org/actinia-core [X]
        -  => Repository synced successfully. Please reload the page.
- look at published releases: https://zenodo.org/account/settings/github/repository/actinia-org/actinia-core

Now, at the next release, publishing actinia on Zenodo hopefully works (again).

**Comment by mmacata** [comment]
It works again :) https://zenodo.org/records/10695986
