### ISSUE TITLE
GRASS GIS 8.4 breaks actinia data models

### ISSUE THREAD

**Issue by ninsbl** [actinia-org/actinia-core#509]
The renaming of location to project breaks actinia information models.

For example, fetching raster info in a GET query results in the following error message:
```
"The model \"RasterInfoModel\" does not have an attribute \"project\""
```

**Comment by mmacata** [comment]
There is already one https://github.com/actinia-org/actinia-api/issues/22 but not with the details found here.

**Comment by ninsbl** [comment]
OK, then I close this one...
