### ISSUE TITLE
Remove `grass-session` pip package for GRASS GIS 8.4 compatibility

### ISSUE THREAD

**Issue by neteler** [actinia-org/actinia-core#533]
(related to #531)

Two more updates are needed for GRASS GIS 8.4 compatibility: the `grass-session` pip package is to be removed as it is incompatible and outdated.

On GRASS-side, this PR has implemented it:
https://github.com/OSGeo/grass/pull/3819

In actinia, here changes are needed (maybe more):

- https://github.com/actinia-org/actinia-core/blob/4c8b9cf150f6f752f5ad48516a1adc2246cad343/docker/actinia-core-alpine/Dockerfile#L18
- https://github.com/actinia-org/actinia-docker/blob/d2e32a5e2cbfdfe9499d75ebae4e2c7631056116/actinia-alpine/Dockerfile#L45

**Comment by mmacata** [comment]
Done with above PR
